stages:
  - publish_launcher
  - publish

publisWindowsExecutable:
  stage: publish_launcher
  tags:
    - windows
  script:
    - ./gradlew -i --no-build-cache clean PackrLauncher:publish

publishLinuxExecutable:
  stage: publish_launcher
  tags:
    - ubuntu
  script:
    - ./gradlew -i --no-build-cache clean PackrLauncher:publish

publishOsxExecutable:
  stage: publish_launcher
  tags:
    - osx
  script:
    - ./gradlew -i --no-build-cache clean PackrLauncher:publish

#publishWindows:
#  stage: publish
#  tags:
#    - windows
#  script:
#    - ./gradlew -i --no-build-cache clean build publish

publishLinux:
  stage: publish
  tags:
    - ubuntu
  script:
    - ./gradlew -i --no-build-cache clean build publish

#publishOsx:
#  stage: publish
#  tags:
#    - osx
#  script:
#    - ./gradlew -i --no-build-cache clean build publish

after_script:
  - echo "End CI"
